# Generated by Django 3.1 on 2021-03-06 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('videoLink', models.CharField(blank=True, max_length=255, null=True)),
                ('header', models.CharField(max_length=255)),
                ('maker', models.CharField(max_length=14)),
                ('pLanguage', models.CharField(max_length=50)),
                ('link', models.SlugField(blank=True, max_length=130, unique=True)),
                ('watcher', models.IntegerField(default=0)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('discription', models.TextField()),
                ('code', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='video.video')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
